export const PLAYER_LIVES = 3;
export const PLAYER_HEALTH = 4;
export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const PLAYER_BULLET_SPEED = 300;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_LIFESPAN = 3;
export const PLAYER_BULLETS_MAX_COUNT = 20;
export const PLAYER_DOUBLE_SHOT_OFFSETS = [-10, 10];
export const PLAYER_POWER_UP_DURATION = 8000;
export const BEST_SCORE_STORAGE_KEY = 'space-defender-best-score';

export const ENEMY_FIGHTER_SCORE = 200;
export const ENEMY_FIGHTER_HEALTH = 2;
export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 5;
export const ENEMY_FIGHTER_BULLET_SPEED = -280;
export const ENEMY_FIGHTER_BULLET_INTERVAL = 2000;
export const ENEMY_FIGHTER_BULLET_MIN_INTERVAL = 1000;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 3;
export const ENEMY_FIGHTER_BULLETS_MAX_COUNT = 10;
export const ENEMY_FIGHTER_GROUP_SPAWN_INTERVAL = 11000;
export const ENEMY_FIGHTER_GROUP_SPAWN_START = 7000;
export const ENEMY_FIGHTER_GROUP_SPAWN_MIN_INTERVAL = 5000;

export const ENEMY_BOSS_SCORE = 800;
export const ENEMY_BOSS_HEALTH = 14;
export const ENEMY_BOSS_ROCK_HEALTH = 3;
export const ENEMY_BOSS_BULLET_SPEED = -240;
export const ENEMY_BOSS_BULLET_INTERVAL = 1300;
export const ENEMY_BOSS_BULLET_LIFESPAN = 4;
export const ENEMY_BOSS_BULLETS_MAX_COUNT = 24;
export const ENEMY_BOSS_BULLET_OFFSETS = [-28, 0, 28];
export const ENEMY_BOSS_BULLET_VERTICAL_SPEED = 185;
export const ENEMY_BOSS_FIRST_ATTACK_DELAY = 1100;
export const ENEMY_BOSS_MOVEMENT_INTERVAL = 3200;
export const ENEMY_BOSS_MOVEMENT_DURATION = 650;
export const ENEMY_BOSS_MOVEMENT_MARGIN = 70;
export const ENEMY_BOSS_FIRST_SCORE = 2000;
export const ENEMY_BOSS_SCORE_INTERVAL = 2000;

export const ENEMY_SCOUT_SCORE = 100;
export const ENEMY_SCOUT_HEALTH = 2;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 40;
export const ENEMY_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 4;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 9;
export const ENEMY_SCOUT_GROUP_SPAWN_INTERVAL = 7500; 
export const ENEMY_SCOUT_GROUP_SPAWN_START = 2500;
export const ENEMY_SCOUT_GROUP_SPAWN_MIN_INTERVAL = 2800;

export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;

export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;

export const POWER_UP_SPAWN_INTERVAL = 9000;
export const POWER_UP_SPAWN_START = 5000;
export const POWER_UP_MOVEMENT_VERTICAL_VELOCITY = 70;

export const DIFFICULTY_LEVEL_SCORE_STEP = 1000;
export const DIFFICULTY_SPAWN_INTERVAL_MULTIPLIER = 0.9;
export const DIFFICULTY_ENEMY_SPEED_LEVEL_MULTIPLIER = 0.14;
export const DIFFICULTY_ENEMY_SPEED_MAX_MULTIPLIER = 1.7;
export const DIFFICULTY_ENEMY_FIRE_RATE_LEVEL_MULTIPLIER = 0.2;
